name: opty testing

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:

    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install conda, test, & build docs
      run: |
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        chmod +x miniconda.sh
        ./miniconda.sh -b -p $HOME/miniconda
        source "$HOME/miniconda/etc/profile.d/conda.sh"
        conda init bash
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda update -q conda
        conda install -n base conda-libmamba-solver
        conda config --set solver libmamba
        conda create -q -n test-env python=${{ matrix.python-version }}
        conda activate test-env
        conda install -y -q sympy cython scipy cyipopt pytest pytest-cov coverage sphinx matplotlib-base openmp
        conda info -a
        conda list
        python setup.py install
        python -c "import opty"
        py.test --cov=opty opty/
        python -m pip install pycompilation
        py.test --cov=opty opty/
        cd docs && make clean && make html && cd ..
